import {
  defineCloudflareConfig,
  type OpenNextConfig,
} from '@opennextjs/cloudflare';

const baseConfig = defineCloudflareConfig();

const originFallbackRoutes = [
  'app/[locale]/(admin)/admin/ai-tasks/page',
  'app/[locale]/(admin)/admin/apikeys/page',
  'app/[locale]/(admin)/admin/categories/[id]/edit/page',
  'app/[locale]/(admin)/admin/categories/add/page',
  'app/[locale]/(admin)/admin/categories/page',
  'app/[locale]/(admin)/admin/chats/page',
  'app/[locale]/(admin)/admin/credits/page',
  'app/[locale]/(admin)/admin/no-permission/page',
  'app/[locale]/(admin)/admin/page',
  'app/[locale]/(admin)/admin/payments/page',
  'app/[locale]/(admin)/admin/permissions/page',
  'app/[locale]/(admin)/admin/posts/[id]/edit/page',
  'app/[locale]/(admin)/admin/posts/add/page',
  'app/[locale]/(admin)/admin/posts/page',
  'app/[locale]/(admin)/admin/roles/[id]/delete/page',
  'app/[locale]/(admin)/admin/roles/[id]/edit-permissions/page',
  'app/[locale]/(admin)/admin/roles/[id]/edit/page',
  'app/[locale]/(admin)/admin/roles/[id]/restore/page',
  'app/[locale]/(admin)/admin/roles/page',
  'app/[locale]/(admin)/admin/settings/[tab]/page',
  'app/[locale]/(admin)/admin/subscriptions/page',
  'app/[locale]/(admin)/admin/users/[id]/edit-roles/page',
  'app/[locale]/(admin)/admin/users/[id]/edit/page',
  'app/[locale]/(admin)/admin/users/page',
  'app/[locale]/(auth)/forgot-password/page',
  'app/[locale]/(auth)/no-permission/page',
  'app/[locale]/(auth)/reset-password/page',
  'app/[locale]/(chat)/chat/[id]/page',
  'app/[locale]/(chat)/chat/history/page',
  'app/[locale]/(chat)/chat/page',
  'app/[locale]/(docs)/docs/[[...slug]]/page',
  'app/[locale]/(landing)/(ai)/ai-audio-generator/page',
  'app/[locale]/(landing)/(ai)/ai-chatbot/page',
  'app/[locale]/(landing)/(ai)/ai-image-generator/page',
  'app/[locale]/(landing)/(ai)/ai-music-generator/page',
  'app/[locale]/(landing)/(ai)/ai-video-generator/page',
  'app/[locale]/(landing)/[slug]/page',
  'app/[locale]/(landing)/activity/ai-tasks/[id]/refresh/page',
  'app/[locale]/(landing)/activity/ai-tasks/page',
  'app/[locale]/(landing)/activity/chats/page',
  'app/[locale]/(landing)/activity/feedbacks/page',
  'app/[locale]/(landing)/activity/page',
  'app/[locale]/(landing)/blog/[slug]/page',
  'app/[locale]/(landing)/blog/category/[slug]/page',
  'app/[locale]/(landing)/blog/page',
  'app/[locale]/(landing)/pricing/page',
  'app/[locale]/(landing)/settings/apikeys/[id]/delete/page',
  'app/[locale]/(landing)/settings/apikeys/[id]/edit/page',
  'app/[locale]/(landing)/settings/apikeys/create/page',
  'app/[locale]/(landing)/settings/apikeys/page',
  'app/[locale]/(landing)/settings/billing/cancel/page',
  'app/[locale]/(landing)/settings/billing/page',
  'app/[locale]/(landing)/settings/billing/retrieve/page',
  'app/[locale]/(landing)/settings/credits/page',
  'app/[locale]/(landing)/settings/invoices/retrieve/page',
  'app/[locale]/(landing)/settings/page',
  'app/[locale]/(landing)/settings/payments/page',
  'app/[locale]/(landing)/settings/profile/page',
  'app/[locale]/(landing)/settings/security/page',
  'app/ads.txt/route',
  'app/api/ai/generate/route',
  'app/api/ai/notify/[provider]/route',
  'app/api/ai/query/route',
  'app/api/chat/info/route',
  'app/api/chat/list/route',
  'app/api/chat/messages/route',
  'app/api/chat/new/route',
  'app/api/chat/route',
  'app/api/docs/search/route',
  'app/api/email/send-email/route',
  'app/api/email/test/route',
  'app/api/email/verify-code/route',
  'app/api/payment/callback/route',
  'app/api/payment/checkout/route',
  'app/api/payment/notify/[provider]/route',
  'app/api/storage/upload-image/route',
  'app/api/user/get-user-credits/route',
  'app/api/user/get-user-info/route',
] as const;

const config: OpenNextConfig = {
  ...baseConfig,
  functions: {
    originFallback: {
      routes: [...originFallbackRoutes],
      patterns: [
        '/admin*',
        '/chat*',
        '/docs*',
        '/ai-*',
        '/blog*',
        '/pricing*',
        '/activity*',
        '/settings*',
        '/forgot-password*',
        '/reset-password*',
        '/no-permission*',
        '/ads.txt',
        '/api/ai/*',
        '/api/chat/*',
        '/api/docs/*',
        '/api/email/*',
        '/api/payment/*',
        '/api/storage/*',
        '/api/user/*',
      ],
    },
  },
};

export default config;
