export const PUBLIC_SETTING_NAMES = [
  'app_name',
  'app_url',
  'app_logo',
  'app_favicon',
  'app_og_image',
  'general_ai_enabled',
  'general_blog_enabled',
  'general_docs_enabled',
  'general_locale_switcher_enabled',
  'general_social_links_enabled',
  'general_social_links',
  'general_support_email',
  'email_auth_enabled',
  'google_auth_enabled',
  'google_one_tap_enabled',
  'google_client_id',
  'github_auth_enabled',
  'select_payment_enabled',
  'default_payment_provider',
  'stripe_enabled',
  'creem_enabled',
  'paypal_enabled',
  'affonso_enabled',
  'promotekit_enabled',
  'crisp_enabled',
  'tawk_enabled',
] as const;

export const publicSettingNames: readonly string[] = PUBLIC_SETTING_NAMES;
