import 'server-only';

import type { Setting } from '../types';

export const adsSettings: Setting[] = [
  {
    name: 'ads_enabled',
    title: 'Ads Enabled',
    type: 'switch',
    value: 'false',
    tip: 'Enable a single active ads provider for the current site.',
    group: 'ads_basic',
    tab: 'ads',
  },
  {
    name: 'ads_provider',
    title: 'Active Provider',
    type: 'select',
    value: 'adsense',
    options: [
      { title: 'AdSense', value: 'adsense' },
      { title: 'Adsterra', value: 'adsterra' },
    ],
    tip: 'Only one ads provider can be active at a time.',
    group: 'ads_basic',
    tab: 'ads',
  },
  {
    name: 'adsense_client_id',
    title: 'AdSense Client ID',
    type: 'text',
    placeholder: 'ca-pub-',
    group: 'adsense',
    tab: 'ads',
  },
  {
    name: 'adsense_slot_landing_inline_primary',
    title: 'AdSense Landing Inline Primary Slot',
    type: 'text',
    placeholder: '1234567890',
    group: 'adsense',
    tab: 'ads',
  },
  {
    name: 'adsense_slot_blog_post_inline',
    title: 'AdSense Blog Post Inline Slot',
    type: 'text',
    placeholder: '1234567890',
    group: 'adsense',
    tab: 'ads',
  },
  {
    name: 'adsense_slot_blog_post_footer',
    title: 'AdSense Blog Post Footer Slot',
    type: 'text',
    placeholder: '1234567890',
    group: 'adsense',
    tab: 'ads',
  },
  {
    name: 'adsterra_mode',
    title: 'Adsterra Mode',
    type: 'select',
    value: 'native_banner',
    options: [
      { title: 'Social Bar', value: 'social_bar' },
      { title: 'Popunder', value: 'popunder' },
      { title: 'Native Banner', value: 'native_banner' },
      { title: 'Display Banner', value: 'display_banner' },
    ],
    tip: 'Choose whether Adsterra runs as a global script mode or as in-page named zones.',
    group: 'adsterra',
    tab: 'ads',
  },
  {
    name: 'adsterra_global_script_src',
    title: 'Adsterra Global Script Src',
    type: 'url',
    placeholder: 'https://example.com/adsterra-global.js',
    tip: 'Use this for Social Bar or Popunder code copied from the Adsterra dashboard.',
    group: 'adsterra',
    tab: 'ads',
  },
  {
    name: 'adsterra_zone_landing_inline_primary_script_src',
    title: 'Adsterra Landing Inline Primary Script Src',
    type: 'url',
    placeholder: 'https://example.com/adsterra-landing-zone.js',
    group: 'adsterra',
    tab: 'ads',
  },
  {
    name: 'adsterra_zone_blog_post_inline_script_src',
    title: 'Adsterra Blog Post Inline Script Src',
    type: 'url',
    placeholder: 'https://example.com/adsterra-blog-inline-zone.js',
    group: 'adsterra',
    tab: 'ads',
  },
  {
    name: 'adsterra_zone_blog_post_footer_script_src',
    title: 'Adsterra Blog Post Footer Script Src',
    type: 'url',
    placeholder: 'https://example.com/adsterra-blog-footer-zone.js',
    group: 'adsterra',
    tab: 'ads',
  },
  {
    name: 'adsterra_ads_txt_entry',
    title: 'Adsterra ads.txt Entry',
    type: 'text',
    placeholder: 'example.com, publisher-id, DIRECT',
    tip: 'Optional. Paste the exact ads.txt line if Adsterra provides one for your account.',
    group: 'adsterra',
    tab: 'ads',
  },
];
