import 'server-only';

import type { Setting } from '../types';

export const paymentSettings: Setting[] = [
  {
    name: 'select_payment_enabled',
    title: 'Select Payment Method Enabled',
    type: 'switch',
    value: 'false',
    tip: 'whether allow users to select payment method, if disabled, the default payment provider will be used',
    placeholder: '',
    group: 'basic_payment',
    tab: 'payment',
  },
  {
    name: 'default_payment_provider',
    title: 'Default Payment Provider',
    type: 'select',
    value: 'stripe',
    options: [
      {
        title: 'Stripe',
        value: 'stripe',
      },
      {
        title: 'Creem',
        value: 'creem',
      },
      {
        title: 'Paypal',
        value: 'paypal',
      },
    ],
    tip: 'Choose the default payment provider to use',
    group: 'basic_payment',
    tab: 'payment',
  },
  {
    name: 'stripe_enabled',
    title: 'Stripe Enabled',
    type: 'switch',
    value: 'false',
    placeholder: '',
    group: 'stripe',
    tab: 'payment',
  },
  {
    name: 'stripe_publishable_key',
    title: 'Stripe Publishable Key',
    type: 'text',
    placeholder: 'pk_xxx',
    group: 'stripe',
    tab: 'payment',
  },
  {
    name: 'stripe_secret_key',
    title: 'Stripe Secret Key',
    type: 'password',
    placeholder: 'sk_xxx',
    group: 'stripe',
    tab: 'payment',
  },
  {
    name: 'stripe_signing_secret',
    title: 'Stripe Signing Secret',
    type: 'password',
    placeholder: 'whsec_xxx',
    tip: 'Stripe Signing Secret is used to verify the webhook notification from Stripe',
    group: 'stripe',
    tab: 'payment',
  },
  {
    name: 'stripe_payment_methods',
    title: 'Stripe Payment Methods',
    type: 'checkbox',
    tip: 'If not set, only card payment method will be enabled.',
    options: [
      { title: 'Card', value: 'card' },
      { title: 'Wechat Pay', value: 'wechat_pay' },
      { title: 'Alipay', value: 'alipay' },
    ],
    value: ['card'],
    group: 'stripe',
    tab: 'payment',
  },
  {
    name: 'creem_enabled',
    title: 'Creem Enabled',
    type: 'switch',
    value: 'false',
    group: 'creem',
    tab: 'payment',
  },
  {
    name: 'creem_environment',
    title: 'Creem Environment',
    type: 'select',
    value: 'sandbox',
    options: [
      { title: 'Sandbox', value: 'sandbox' },
      { title: 'Production', value: 'production' },
    ],
    group: 'creem',
    tab: 'payment',
  },
  {
    name: 'creem_api_key',
    title: 'Creem API Key',
    type: 'password',
    placeholder: 'creem_xxx',
    group: 'creem',
    tab: 'payment',
  },
  {
    name: 'creem_signing_secret',
    title: 'Creem Signing Secret',
    type: 'password',
    placeholder: 'whsec_xxx',
    group: 'creem',
    tab: 'payment',
    tip: 'Creem Signing Secret is used to verify the webhook notification from Creem',
  },
  {
    name: 'creem_product_ids',
    title: 'Creem Product IDs Mapping',
    type: 'textarea',
    attributes: {
      rows: 6,
    },
    placeholder: `{
  "starter": "prod_xxx",
  "standard-monthly": "prod_xxx",
  "premium-yearly": "prod_xxx"
}`,
    group: 'creem',
    tab: 'payment',
    tip: 'Map the product_id in pricing table to <a href="https://www.creem.io/dashboard/products" class="text-primary" target="_blank">payment_product_id</a> created in Creem. Must be a valid JSON object.',
  },
  {
    name: 'paypal_enabled',
    title: 'Paypal Enabled',
    type: 'switch',
    value: 'false',
    group: 'paypal',
    tab: 'payment',
  },
  {
    name: 'paypal_environment',
    title: 'Paypal Environment',
    type: 'select',
    value: 'sandbox',
    options: [
      { title: 'Sandbox', value: 'sandbox' },
      { title: 'Production', value: 'production' },
    ],
    group: 'paypal',
    tab: 'payment',
  },
  {
    name: 'paypal_client_id',
    title: 'Paypal Client ID',
    type: 'text',
    placeholder: 'paypal_xxx',
    group: 'paypal',
    tab: 'payment',
  },
  {
    name: 'paypal_client_secret',
    title: 'Paypal Client Secret',
    type: 'password',
    placeholder: 'paypal_xxx',
    group: 'paypal',
    tab: 'payment',
  },
];
